apiVersion: v1
kind: Service
metadata:
  name: ord-reference-app
  namespace: default
  labels:
    app: ord-reference-app
spec:
  selector:
    app: ord-reference-app
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
